package:
  name: gamma-facet
  version: 1.0.0

source:
  git_url: {{FACET_PATH}}/facet

build:
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip>=19.1
    - python{{ environ.get('FACET_V_PYTHON_BUILD', '=3.8.*') }}
  run:
    - python{{ environ.get('FACET_V_PYTHON', '>=3.6,<4') }}
    - pandas{{ environ.get('FACET_V_PANDAS', '>=0.24,<1.2') }}
    - numpy{{ environ.get('FACET_V_NUMPY', '>=1.16,<1.20') }}
    - scipy{{ environ.get('FACET_V_SCIPY', '>=1.2,<1.6') }}
    - matplotlib{{ environ.get('FACET_V_MATPLOT', '>=3.1,<3.4') }}
    - scikit-learn{{ environ.get('FACET_V_SKLEARN', '>=0.21,<0.24') }}
    - shap{{ environ.get('FACET_V_SHAP', '>=0.34,<0.36') }}
    - gamma-pytools=1.0.*
    - gamma-sklearndf=1.0.*
    - pyyaml>=5
test:
  imports:
    - facet
    - facet.crossfit
    - facet.inspection
    - facet.selection
    - facet.validation
    - facet.simulation
  requires:
    - pytest=5.2.*
  commands:
    - conda list
    - python -c 'import facet;
                 import os;
                 assert facet.__version__ == os.environ["PKG_VERSION"]'
    - pytest -vs ${FACET_PATH}/pytools/test
    - pytest -vs ${FACET_PATH}/sklearndf/test
    - pytest -vs ${FACET_PATH}/facet/test
